/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedUserRouteRouteImport } from './routes/_authenticated/user/route'
import { Route as AuthenticatedMainRouteRouteImport } from './routes/_authenticated/main/route'
import { Route as AuthenticatedLocationRouteRouteImport } from './routes/_authenticated/location/route'
import { Route as AuthenticatedMainIndexRouteImport } from './routes/_authenticated/main/index'
import { Route as AuthenticatedMainStoreIdRouteImport } from './routes/_authenticated/main/$storeId'
import { Route as AuthenticatedUserCouponRouteRouteImport } from './routes/_authenticated/user/coupon/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserRouteRoute = AuthenticatedUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMainRouteRoute = AuthenticatedMainRouteRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationRouteRoute =
  AuthenticatedLocationRouteRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainIndexRoute = AuthenticatedMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMainRouteRoute,
} as any)
const AuthenticatedMainStoreIdRoute =
  AuthenticatedMainStoreIdRouteImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedUserCouponRouteRoute =
  AuthenticatedUserCouponRouteRouteImport.update({
    id: '/coupon',
    path: '/coupon',
    getParentRoute: () => AuthenticatedUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/location': typeof AuthenticatedLocationRouteRoute
  '/main': typeof AuthenticatedMainRouteRouteWithChildren
  '/user': typeof AuthenticatedUserRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/user/coupon': typeof AuthenticatedUserCouponRouteRoute
  '/main/$storeId': typeof AuthenticatedMainStoreIdRoute
  '/main/': typeof AuthenticatedMainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/location': typeof AuthenticatedLocationRouteRoute
  '/user': typeof AuthenticatedUserRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/user/coupon': typeof AuthenticatedUserCouponRouteRoute
  '/main/$storeId': typeof AuthenticatedMainStoreIdRoute
  '/main': typeof AuthenticatedMainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/location': typeof AuthenticatedLocationRouteRoute
  '/_authenticated/main': typeof AuthenticatedMainRouteRouteWithChildren
  '/_authenticated/user': typeof AuthenticatedUserRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/user/coupon': typeof AuthenticatedUserCouponRouteRoute
  '/_authenticated/main/$storeId': typeof AuthenticatedMainStoreIdRoute
  '/_authenticated/main/': typeof AuthenticatedMainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/location'
    | '/main'
    | '/user'
    | '/home'
    | '/user/coupon'
    | '/main/$storeId'
    | '/main/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/location'
    | '/user'
    | '/home'
    | '/user/coupon'
    | '/main/$storeId'
    | '/main'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/location'
    | '/_authenticated/main'
    | '/_authenticated/user'
    | '/_authenticated/home'
    | '/_authenticated/user/coupon'
    | '/_authenticated/main/$storeId'
    | '/_authenticated/main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/location': {
      id: '/_authenticated/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof AuthenticatedLocationRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main/': {
      id: '/_authenticated/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof AuthenticatedMainIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/main/$storeId': {
      id: '/_authenticated/main/$storeId'
      path: '/$storeId'
      fullPath: '/main/$storeId'
      preLoaderRoute: typeof AuthenticatedMainStoreIdRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/user/coupon': {
      id: '/_authenticated/user/coupon'
      path: '/coupon'
      fullPath: '/user/coupon'
      preLoaderRoute: typeof AuthenticatedUserCouponRouteRouteImport
      parentRoute: typeof AuthenticatedUserRouteRoute
    }
  }
}

interface AuthenticatedMainRouteRouteChildren {
  AuthenticatedMainStoreIdRoute: typeof AuthenticatedMainStoreIdRoute
  AuthenticatedMainIndexRoute: typeof AuthenticatedMainIndexRoute
}

const AuthenticatedMainRouteRouteChildren: AuthenticatedMainRouteRouteChildren =
  {
    AuthenticatedMainStoreIdRoute: AuthenticatedMainStoreIdRoute,
    AuthenticatedMainIndexRoute: AuthenticatedMainIndexRoute,
  }

const AuthenticatedMainRouteRouteWithChildren =
  AuthenticatedMainRouteRoute._addFileChildren(
    AuthenticatedMainRouteRouteChildren,
  )

interface AuthenticatedUserRouteRouteChildren {
  AuthenticatedUserCouponRouteRoute: typeof AuthenticatedUserCouponRouteRoute
}

const AuthenticatedUserRouteRouteChildren: AuthenticatedUserRouteRouteChildren =
  {
    AuthenticatedUserCouponRouteRoute: AuthenticatedUserCouponRouteRoute,
  }

const AuthenticatedUserRouteRouteWithChildren =
  AuthenticatedUserRouteRoute._addFileChildren(
    AuthenticatedUserRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedLocationRouteRoute: typeof AuthenticatedLocationRouteRoute
  AuthenticatedMainRouteRoute: typeof AuthenticatedMainRouteRouteWithChildren
  AuthenticatedUserRouteRoute: typeof AuthenticatedUserRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLocationRouteRoute: AuthenticatedLocationRouteRoute,
  AuthenticatedMainRouteRoute: AuthenticatedMainRouteRouteWithChildren,
  AuthenticatedUserRouteRoute: AuthenticatedUserRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
